apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: instavote
spec:
  clusterIP: 10.96.237.121
  clusterIPs:
    - 10.96.237.121
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: "80"
      nodePort: 30300
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: vote
  sessionAffinity: None
  type: NodePort
