#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
spec:
  dependsOn:
    - name: redis
commonLabels:
  project: instavote
  env: dev

commonAnnotations:
  supported-by: "sre@example.com"
